### ISSUE TITLE
リリース前に google analytics を導入する

### ISSUE THREAD

**Issue by kojitaniguchi** [whooku/band_birthday#15]
忘れないよう！！！！

**Comment by kojitaniguchi** [comment]
### 1. 登録する
https://marketingplatform.google.com/about/analytics/
右上の **`アナリティクスにログイン`** を押す

[![Image from Gyazo](https://i.gyazo.com/e01614520e44cc29b4a1030b500736df.jpg)](https://gyazo.com/e01614520e44cc29b4a1030b500736df)

### 2. ここまで行けたらok
[![Image from Gyazo](https://i.gyazo.com/0505ca34c1e6d568c79b1f7cb6c04034.png)](https://gyazo.com/0505ca34c1e6d568c79b1f7cb6c04034)

**Comment by whooku** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160697961-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160697961-1');
</script>
