### ISSUE TITLE
【TOP】自動で周る吹き出し

### ISSUE THREAD

**Issue by kojitaniguchi** [whooku/band_birthday#8]
# イメージサイト
http://orbital-kaitori.com/

# 参考実装
これの autoplay
http://kenwheeler.github.io/slick/

**Comment by whooku** [comment]
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>



<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
      <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
      <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

      <script type="text/javascript">
      $('.loves').slick({
            slidesToShow: 3,
            autoplay: true,
            autoplaySpeed: 2000,
            arrows: false
            });
      </script>
